  # Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97b3ab822f5de91ebb9986761487801d01292c6e52c7e11f5364dce5145a6c51dce22dc3face7ee6a95089c6228f656311a0c85aa910fcfd6665b2077ecef62d

test:
  secret_key_base: 858555740f71b8b2634014c52e53a846e9edac62a98c18b83e5e716bb89db74b7de7309aaf83ea8fe7ef7dfc07e3128477e44730c041da30c417c7d83590d91e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
